Cezary Tytko 118873

In [2]:
import numpy as np
print(np.__version__)


1.23.5


Zadanie 1
Funkcja all sprawdza czy wszystkie elementy są true (logiczna koniunkcja)

In [7]:
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])
B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])
C = np.array([[True, False, False],
              [True, True, True]])
D = np.array([0.1, 0.3])

print(A.all())
print(B.all())
print(C.all())
print(D.all())

True
False
False
True


Zadanie 2
Możemy podać dodatkowy parametr  wskazujący na oś, w takim przypadku otrzymamy tablicę wyników dla każdego z wierszy bądź kolumny w zależności od wybranej osi

In [11]:
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])
B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])
C = np.array([[True, False, False],
              [True, True, True]])
print(A.all(axis=1))
print(B.all(axis=1))
print(C.all(axis=1))


[ True  True]
[ True False]
[False  True]


Zadanie 3
Metoda any sprawdza  czy którykolwiek element jest true (logiczna alternatywa)

In [14]:
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])
B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])
C = np.array([[True, False, False],
              [True, True, True]])
print(A.any())
print(B.any())
print(C.any())

True
True
True


Zadanie 4
arange tworzy nam tablicę z wybranego przedziału liczb i ze wskazanym krokiem 

In [16]:
tab = np.arange(10,100,1)
print(tab)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


Zadanie 5
Metodą reshape możemy zmienić wymiar tablicy numpy

In [20]:
tab2 = tab.reshape(9,10)
print(tab2)

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


Zadanie 6
eye tworzy macierz jednostkową, dodatkowo rzutujemy ją na typ int

In [6]:
tabEye = np.eye(6).astype(int)
print(tabEye)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


Zadanie 7
na obiekcie random z biblioteki numpy możemy wykonywać operacje jak dal klasycznej wersji tylko że dla tablic 

In [34]:
import random
np.random.seed(10)
tabRandom = np.random.rand(30)
print(tabRandom) 

[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981 0.68535982 0.95339335
 0.00394827 0.51219226 0.81262096 0.61252607 0.72175532 0.29187607
 0.91777412 0.71457578 0.54254437 0.14217005 0.37334076 0.67413362
 0.44183317 0.43401399 0.61776698 0.51313824 0.65039718 0.60103895]


Zadanie 8
Tworzymy tabelę z losowymi wartościami rozkładu normalnego, w dwóch wersjach. Pierwszej z wartościami domyślnymi i drugiej gdzie podajemy parametry rozkładu normalnego N(0,1)

In [8]:
np.random.seed(20)
tabRandom = np.random.randn(10,4)
print(tabRandom) 
print()
np.random.seed(20)
tabRandom = np.random.normal(0, 1, size=(10,4))
print(tabRandom) 

[[ 0.88389311  0.19586502  0.35753652 -2.34326191]
 [-1.08483259  0.55969629  0.93946935 -0.97848104]
 [ 0.50309684  0.40641447  0.32346101 -0.49341088]
 [-0.79201679 -0.84236793 -1.27950266  0.24571517]
 [-0.0441948   1.56763255  1.05110868  0.40636843]
 [-0.1686461  -3.18970279  1.12013226  1.33277821]
 [-0.24333877 -0.13003071 -0.10901737  1.55618644]
 [ 0.12877835 -2.06694872 -0.88549315 -1.10457948]
 [ 0.93286635  2.059838   -0.93493796 -1.61299022]
 [ 0.52706972 -1.55110074  0.32961334 -1.13652654]]

[[ 0.88389311  0.19586502  0.35753652 -2.34326191]
 [-1.08483259  0.55969629  0.93946935 -0.97848104]
 [ 0.50309684  0.40641447  0.32346101 -0.49341088]
 [-0.79201679 -0.84236793 -1.27950266  0.24571517]
 [-0.0441948   1.56763255  1.05110868  0.40636843]
 [-0.1686461  -3.18970279  1.12013226  1.33277821]
 [-0.24333877 -0.13003071 -0.10901737  1.55618644]
 [ 0.12877835 -2.06694872 -0.88549315 -1.10457948]
 [ 0.93286635  2.059838   -0.93493796 -1.61299022]
 [ 0.52706972 -1.55110074  0.