In [3]:
import numpy as np

## Dane studenta

Cezary Tytko 118873

# Zadania do samodzielnego wykonania

## Ćwiczenie 1

Poniżej podano dwie tablice A i B:
Połącz te tablice w następujący sposób:

In [2]:
A = np.array([[3, 4, 5],
[8, 3, 1]])
B = np.array([[0, 5, 2],
[4, 2, 1]])

### Miejsce na rozwiązanie

In [8]:
C = np.concatenate((A,B),axis=0)
print(C)

[[3 4 5]
 [8 3 1]
 [0 5 2]
 [4 2 1]]


## Ćwiczenie 2

Podana jest poniższa tablica zawierająca dane data oraz tablica zawierającą klasę docelową target
dla danego wiersza:
Połącz te tablice w jedną tak jak pokazano poniżej:
array([[4.3, 4.2, 0. ], [3.1, 3.6, 1. ]])

In [9]:
data = np.array([[4.3, 4.2],
[3.1, 3.6]])
target = np.array([[0],
[1]])

result_array = np.column_stack((data, target))

print(result_array)

[[4.3 4.2 0. ]
 [3.1 3.6 1. ]]


## Ćwiczenie 3

Podane są następujące trzy jednowymiarowe tablice:
Wydrukuj wynik do konsoli.
Oczekiwany wynik: [[1.6 0.4 1.4] [0.9 1.3 0.3] [2.2 3.2 1.2]]
Przekształć każdą z tych tablic w kolumnę i połącz je w jedną dużą tablicę. Wydrukuj wynik do
konsoli. Wskazówka: Użyj funkcji np.column_stack()

### Miejsce na rozwiązanie

In [10]:
feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])

column_feature1 = feature1[:, np.newaxis]
column_feature2 = feature2[:, np.newaxis]
column_feature3 = feature3[:, np.newaxis]

result_array = np.column_stack((column_feature1, column_feature2, column_feature3))

# Wydrukuj wynik
print(result_array)

[[1.6 0.4 1.4]
 [0.9 1.3 0.3]
 [2.2 3.2 1.2]]


## Ćwiczenie 4

Podana jest następująca tablica numpy A:
Podziel tablicę na trzy części tak, aby dwie pierwsze kolumny utworzyły tablicę A1, cztery kolejne
tablicę A2 i ostatnie dwie tablicę A3.
Wydrukuj wynik do konsoli. Wskazówka: Użyj funkcji np.split()

In [12]:
np.random.seed(42)
A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1
print(A)
A[1:-1, 1:-1] = 1
print(A)
A[:, [0, -1]] = 0
A[[0, -1],:] = 0
A = A.astype(float)
print(A)
A1, A2, A3 = np.split(A, [2, 6], axis=1)

print("Tablica A1:")
print(A1)
print("\nTablica A2:")
print(A2)
print("\nTablica A3:")
print(A3)

[[0 0 4 6 2 4 1 1]
 [0 0 6 2 2 4 1 1]
 [0 0 1 3 5 5 1 1]
 [0 0 3 1 5 4 1 1]
 [0 0 2 6 1 3 1 1]]
[[0 0 4 6 2 4 1 1]
 [0 1 1 1 1 1 1 1]
 [0 1 1 1 1 1 1 1]
 [0 1 1 1 1 1 1 1]
 [0 0 2 6 1 3 1 1]]
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
Tablica A1:
[[0. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 0.]]

Tablica A2:
[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]]

Tablica A3:
[[0. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 0.]]


## Ćwiczenie 5

Podana jest następująca tablica numpy A:
Oblicz łączną liczbę niezerowych elementów dla tej tablicy. Wydrukuj wynik do konsoli.

In [12]:
np.random.seed(42)
A = np.random.randint(low=0, high=2, size=(10, 6))

nonzero_count = np.count_nonzero(A)

print("Łączna liczba niezerowych elementów w tablicy A:", nonzero_count)

Łączna liczba niezerowych elementów w tablicy A: 31


## Ćwiczenie 6

Podana jest tablica numpy A:
Ustaw opcję biblioteki numpy tak, aby wydrukować tablicę z określoną precyzją. Ustaw jego
wartość na 4 i wydrukuj tablicę A do konsoli.

In [13]:
np.random.seed(42)
np.set_printoptions(precision=4)
A = np.random.randn(10, 4)

print("Tablica A z precyzją 4:")
print(A)

Tablica A z precyzją 4:
[[ 0.4967 -0.1383  0.6477  1.523 ]
 [-0.2342 -0.2341  1.5792  0.7674]
 [-0.4695  0.5426 -0.4634 -0.4657]
 [ 0.242  -1.9133 -1.7249 -0.5623]
 [-1.0128  0.3142 -0.908  -1.4123]
 [ 1.4656 -0.2258  0.0675 -1.4247]
 [-0.5444  0.1109 -1.151   0.3757]
 [-0.6006 -0.2917 -0.6017  1.8523]
 [-0.0135 -1.0577  0.8225 -1.2208]
 [ 0.2089 -1.9597 -1.3282  0.1969]]


## Ćwiczenie 7

Podana jest następująca tablica numpy A:
Ustaw wartość precyzji na 8 oraz odpowiednią opcję biblioteki numpy tak, aby pominąć notację
matematyczną. Wydrukuj tablicę A do konsoli.Wskazówka: Użyj funkcji np.intersect1d().

In [14]:
A = np.array([1.2e-6, 1.7e-7])
np.set_printoptions(precision=8, suppress=True)

print("Tablica A z precyzją 8 i uniknięciem notacji matematycznej:")
print(A)

Tablica A z precyzją 8 i uniknięciem notacji matematycznej:
[0.0000012  0.00000017]


## Ćwiczenie 8

Podana jest następująca tablica numpy A:
Usuń trzecią kolumnę z tablicy A. Resztę tablicy wydrukuj do konsoli.

In [15]:
np.random.seed(42)
A = np.random.randn(8, 4)
A_without_third_column = np.delete(A, 2, axis=1)

print("Tablica A bez trzeciej kolumny:")
print(A_without_third_column)

Tablica A bez trzeciej kolumny:
[[ 0.49671415 -0.1382643   1.52302986]
 [-0.23415337 -0.23413696  0.76743473]
 [-0.46947439  0.54256004 -0.46572975]
 [ 0.24196227 -1.91328024 -0.56228753]
 [-1.01283112  0.31424733 -1.4123037 ]
 [ 1.46564877 -0.2257763  -1.42474819]
 [-0.54438272  0.11092259  0.37569802]
 [-0.60063869 -0.29169375  1.85227818]]


## Ćwiczenie 9

Dana jest jednowymiarowa tablica v (wektor):
Oblicz normę wektora v. Wydrukuj wynik do konsoli.

In [16]:
v = np.array([3, 4, -2])
vector_norm = np.linalg.norm(v)

print("Norma wektora v:", vector_norm)

Norma wektora v: 5.385164807134504


## Ćwiczenie 10

Podana jest poniższa tablica numpy A:
Ustaw opcję biblioteki numpy tak, aby wydrukować 10 elementów brzegowych i następnie wydrukuj
tablicę A


In [17]:
A = np.random.randint(10, size=(100, 30))
 
np.set_printoptions(edgeitems=10)

A = np.random.randint(10, size=(100, 30))

print("Tablica A z 10 elementami brzegowymi:")
print(A)

Tablica A z 10 elementami brzegowymi:
[[5 0 3 0 1 4 7 7 2 3 ... 4 9 4 2 6 5 3 1 8 0]
 [3 0 5 3 4 4 8 0 1 5 ... 4 6 3 2 0 7 2 1 3 2]
 [0 2 1 7 5 8 7 9 2 4 ... 1 5 5 4 5 6 4 0 7 3]
 [8 9 5 0 2 2 9 3 5 6 ... 2 4 1 2 3 6 2 8 7 3]
 [0 0 0 0 7 2 5 2 4 6 ... 7 2 7 8 2 2 1 7 9 0]
 [7 6 6 2 0 3 8 4 0 4 ... 8 1 3 5 2 7 2 1 2 5]
 [1 7 0 6 1 9 5 1 1 9 ... 4 6 0 0 8 4 4 2 4 2]
 [8 8 5 0 6 6 9 9 3 7 ... 6 7 1 6 1 1 7 1 8 0]
 [8 0 9 9 1 5 5 0 6 7 ... 1 3 3 1 2 2 0 5 7 2]
 [4 0 9 6 9 0 8 7 6 9 ... 4 3 2 2 4 9 0 4 5 6]
 ...
 [6 0 2 5 3 6 2 0 8 5 ... 1 3 8 5 7 1 6 5 8 6]
 [0 7 9 2 1 2 5 2 9 4 ... 7 7 5 3 2 2 5 7 6 0]
 [5 6 6 8 9 4 0 1 3 4 ... 3 6 1 1 5 1 5 1 3 6]
 [7 2 8 1 7 7 3 0 0 1 ... 1 0 4 8 7 3 4 4 5 2]
 [4 1 9 0 0 9 6 1 3 4 ... 8 4 7 8 4 9 8 1 8 3]
 [5 5 5 1 6 5 0 1 6 0 ... 3 5 1 6 1 9 7 7 0 7]
 [1 5 0 4 6 9 0 1 6 5 ... 6 7 5 5 9 0 3 0 3 1]
 [4 9 8 9 2 7 2 5 3 7 ... 8 6 2 5 3 2 8 9 1 0]
 [1 6 9 0 5 6 8 7 5 2 ... 5 4 0 2 0 4 4 5 7 9]
 [0 3 9 0 8 6 6 4 6 1 ... 8 3 0 5 4 9 5 2 1 5]]


# Wnioski i sugestie do ćwiczeń

Wnioski: ćwieczenia nie sprawiły problemu, szczegulnie przydatne moga być funkcje takie jak column_stack, concatenate, orez split. Natomiast set_printoptions bedzie bardzo potrzebna przy ocenie i analizie danych.