In [1]:
import numpy as np

## Dane studenta

Cezary Tytko 118873

# Zadania do samodzielnego wykonania

## Ćwiczenie 1

Zbuduj tablicę składającą się ze średnich arytmetycznych odpowiednich elementów tablic A i B.
Wydrukuj wynik do konsoli.

In [2]:
A = np.array([[3, 4, 9, 2], [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5], [6, 3, 1, 6]])

### Miejsce na rozwiązanie

In [3]:
srednie_arytmetyczne = (A + B) / 2
print(srednie_arytmetyczne)

1.1 Wynik:
[[3.5 3.5 5.5 3.5]
 [5.5 3.  1.5 5.5]]


## Ćwiczenie 2

Wykonaj mnożenie tablic A i B element po elemencie. Wydrukuj wynik do konsoli.

In [4]:
mnozenie_element_po_elemencie = A * B
print(mnozenie_element_po_elemencie)


1.2 Wynik:
[[12 12 18 10]
 [30  9  2 30]]


## Ćwiczenie 3

Wyznacz pierwiastek z każdego elementu tablicy A. Wydrukuj wynik do konsoli. Wskazówka: Użyj
funkcji np.sqrt()

### Miejsce na rozwiązanie

In [5]:
A = np.array([[3, 4, 9, 2], [5, 3, 2, 5]])
pierwiastki = np.sqrt(A)
print(pierwiastki)

[[1.73205081 2.         3.         1.41421356]
 [2.23606798 1.73205081 1.41421356 2.23606798]]


## Ćwiczenie 4

Sprawdź twierdzenie Pitagorasa dla sinusów i cosinusów wykorzystując tablicę A i następnie porów-
naj wynik z tablicą B. Użyj funkcji np.allclose(). Wydrukuj wynik do konsoli. Wskazówka: Użyj
funkcji np.sin() oraz np.cos().

In [6]:
A = np.linspace(0, np.pi / 2, 20)
B = np.full(shape=(20,), fill_value=1, dtype='float')

sinusy = np.sin(A)
cosinusy = np.cos(A)
pitagoras = np.allclose(np.square(sinusy) + np.square(cosinusy), B)
print(pitagoras)

True


## Ćwiczenie 5

Dane są dwie dwuwymiarowe tablice numpy A i B:
- A - macierz o kształcie (3,2)
- B - macierz o kształcie (2,3)
Wykonaj mnożenie macierzy A i B. Wydrukuj wynik do konsoli. Wskazówka: Użyj funkcji
np.dot()

In [7]:
A = np.array([[2, 3], [-4, 2], [5, 0]])
B = np.array([[4, 3, 2], [-1, 0, 2]])
mnozenie_macierzy = np.dot(A, B)
print(mnozenie_macierzy)

[[  5   6  10]
 [-18 -12  -4]
 [ 20  15  10]]


## Ćwiczenie 6

Oblicz wyznacznik macierzy A. Wydrukuj wynik do konsoli. Wskazówka: Użyj funkcji
np.linalg.det()

In [8]:
A = np.array([[-2, 0, 4], [5, 2, -1], [-4, 2, 4]])
wyznacznik_A = np.linalg.det(A)
print(wyznacznik_A)

51.999999999999986


## Ćwiczenie 7

Oblicz wartości własne i odpowiadające im wektory własne macierzy A. Wydrukuj wynik do konsoli.
Wskazówka: Użyj funkcji np.linalg.eig()

In [11]:
A = np.array([[5, 8, 16], [4, 1, 8], [-4, 4, -11]])
wartosci_wlasne, wektory_wlasne = np.linalg.eig(A)
print("Wartości własne:")
print(wartosci_wlasne)
print("\nWektory własne:")
print(wektory_wlasne)

Wartości własne:
[-9.24621125 -3.          7.24621125]

Wektory własne:
[[-6.26164716e-01 -8.94427191e-01  8.90159406e-01]
 [-3.13082358e-01  2.82399734e-16  4.45079703e-01]
 [ 7.14070855e-01  4.47213595e-01 -9.75719719e-02]]


## Ćwiczenie 8

Znajdź macierz odwrotną do macierzy A. Wydrukuj wynik do konsoli. Wskazówka: Użyj funkcji
np.linalg.inv()

In [12]:
A = np.array([[5, 8, 16], [4, 1, 8], [-4, 4, -11]])
macierz_odwrotna_A = np.linalg.inv(A)
print(macierz_odwrotna_A)


1.8 Wynik:
[[-0.21393035  0.75621891  0.23880597]
 [ 0.05970149  0.04477612  0.11940299]
 [ 0.09950249 -0.25870647 -0.13432836]]


## Ćwiczenie 9

Znajdź ślad macierzy kwadratowej G (suma elementów na głównej przekątnej). Wydrukuj wynik
do konsoli. Wskazówka: Użyj funkcji p.trace()

In [14]:
G = np.array([[5, 8, 16], [4, 1, 8], [-4, 4, -11]])
slad_G = np.trace(G)
print(slad_G)

-5


## Ćwiczenie 10

Przekształć tablicę B tak, aby móc wykonać mnożenie macierzy A￿B. Wykonaj to mnożenie.
Wydrukuj wynik do konsoli

In [16]:
A = np.array([[2, 0], [4, 2], [5, 3], [4, 2]])
B = np.array([[4, 0, 2, 1, 1, 0, 2, 9]])
B_zmieniona = B.reshape((2, 4))
mnozenie_macierzy_A_B = np.dot(A, B_zmieniona)
print(mnozenie_macierzy_A_B)

[[ 8  0  4  2]
 [18  0 12 22]
 [23  0 16 32]
 [18  0 12 22]]


# Wnioski i sugestie do ćwiczeń

Wnioski: ćwieczenia nie sprawiły problemu, szczegulnie przydatne moga być funkcje takie jak inv, det z numpy.linalg które pozwalają liczyć przydatne własnosći macierzy 