In [1]:
import numpy as np

## Dane studenta

Cezary Tytko 118873

# Zadania do samodzielnego wykonania

## Ćwiczenie 1

Wygeneruj następującą tablicę numpy:

In [21]:
A = np.array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Zapisz tablicę do pliku tekstowego o nazwie `array.txt` z dwoma miejscami po przecinku, załaduj plik z powrotem do innej zmiennej i wydrukuj jej zawartość do konsoli.

Wskazówka: Użyj funkcji `np.savetxt()` oraz `np.loadtxt()`.

### Miejsce na rozwiązanie

In [7]:
np.savetxt('array.txt',A)
B = np.loadtxt('array.txt')
print(B)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


## Ćwiczenie 2

Listę z zadania 1 wczytaj do nowej zmiennej, a następnie przekształć ją na listę a wynik wydrukuj w konsoli.
Wskazówka: Użyj metody `np.array.tolist()`.

### Miejsce na rozwiązanie

In [8]:
C = A.tolist()
print(C)

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]


## Ćwiczenie 3

Listę z zadania 1 przekształć zamieniająć pierwszy i ostatni wiersz ze sobą.

Wydrukuj wynik do konsoli.

### Miejsce na rozwiązanie

In [23]:
a = C[0]
C[0] = C[2]
C[2] = a
print(C)

[[8, 9, 10, 11], [4, 5, 6, 7], [0, 1, 2, 3]]


## Ćwiczenie 4

Następującą tablicę numpy:

In [24]:
A = np.array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

przekształć w tablicę poniżej:

In [ ]:
array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

Wydrukuj wynik do konsoli.
Wskazówka: Użyj funkcji `np.pad()`.

### Miejsce na rozwiązanie

In [26]:
B = np.pad(A,1)
print(B)

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


## Ćwiczenie 5

Następującą tablicę numpy:

In [84]:
A = np.array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

przekształć w tablicę poniżej:

In [ ]:
array([[10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0],
       [10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0],
       [10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0]])

Wydrukuj wynik do konsoli.
Wskazówka: Użyj operatora wycinania i przypisz odpowiednie wartości.

### Miejsce na rozwiązanie

In [85]:
A[::2,::2] = 10
A[1::2,::2] = 5
print(A)

[[10  0 10  0 10  0]
 [ 5  0  5  0  5  0]
 [10  0 10  0 10  0]
 [ 5  0  5  0  5  0]
 [10  0 10  0 10  0]
 [ 5  0  5  0  5  0]]


## Ćwiczenie 6

Korzystając z funkcji poniżej wygeneruj dwie tablice A i B a następnie połącz je w jedną. Wynik wydrukuj w konsoli.

In [27]:
A = np.arange(12).reshape(-1, 4)
B = np.array([[4, 3, 7, 2],
              [0, 5, 2, 6]])

### Miejsce na rozwiązanie

In [34]:
print(A)
print(B)
C = np.concatenate((A,B), 0) 
print(C)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[4 3 7 2]
 [0 5 2 6]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 4  3  7  2]
 [ 0  5  2  6]]


## Ćwiczenie 7

Z podanych tablic A i B poniżej, wyodrębnij wspólne elementy (przecięcie) tablic. Wydrukuj wynik do konsoli.

In [ ]:
A = np.arange(8).reshape(-1, 4)
B = np.array([[9, 10, 11, 3],
              [2, 8, 0, 9]]) 

Wskazówka: Użyj funkcji `np.intersect1d()`.

### Miejsce na rozwiązanie

In [35]:
C = np.intersect1d(A,B)
print(C)

[0 2 3 4 5 6 7]


## Ćwiczenie 8

Podano następującą tablicę numpy A. Znajdź unikalne wartości tej tablicy. Wydrukuj wynik do konsoli.

In [36]:
A = np.array([[5, 1, 2, 1, 2],
              [9, 1, 9, 7, 5],
              [4, 1, 5, 7, 9]])

### Miejsce na rozwiązanie

In [37]:
X = np.unique(A)
print(X)

[1 2 4 5 7 9]


## Ćwiczenie 9

Podana jest poniższa tablica:

In [38]:
A = np.array([[0.4, 0.3, 0.3],
              [0.1, 0.1, 0.8],
              [0.2, 0.5, 0.3]])

Zwróć indeksy z maksymalnymi wartościami dla danego wiersza. Wydrukuj wynik do konsoli.

### Miejsce na rozwiązanie

In [40]:
X = A.max(1)
print(X)

[0.4 0.8 0.5]


## Ćwiczenie 10

Posortuj tablicę A:
- według wiersza (rosnąco),
- według kolumny (rosnąco).

In [71]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])

Wydrukuj wynik do konsoli.

### Miejsce na rozwiązanie

In [72]:
X1 = np.sort(A, axis=1)
X2 = np.sort(A, axis=0)
print(X1)
print('----------------------------------------')
print(X2)

[[ 3.49  4.99  9.99]
 [ 1.99  4.99  9.99]
 [ 2.39  7.29 14.99]]
----------------------------------------
[[ 1.99  2.39  4.99]
 [ 4.99  3.49  7.29]
 [14.99  9.99  9.99]]


## Ćwiczenie 11

Wyodrębnij wszystkie elementy tablicy A o wartości większej niż 8. Wydrukuj wynik do konsoli.

In [ ]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])

### Miejsce na rozwiązanie

In [73]:
X = A > 8
print(A[X])


[ 9.99  9.99 14.99]


array([[ 4.99,  3.49,  9.99],
       [ 1.99,  9.99,  4.99],
       [14.99,  2.39,  7.29]])

## Ćwiczenie 12

Podana jest następująca tablica A. Zastąp elementy większe niż 10 wartością stałą 10.

In [77]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])

Wydrukuj wynik do konsoli.

### Miejsce na rozwiązanie

In [78]:
X = A > 10
A[X] = 10.
print(A)

[[ 4.99  3.49  9.99]
 [ 1.99  9.99 10.  ]
 [10.    2.39  7.29]]


## Ćwiczenie 13

Przedstaw poniższą dwuwymiarową tablicę A jako 'spłaszczoną' jednowymiarową tablicę. Wydrukuj wynik do konsoli.

In [80]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])

Wskazówka: Użyj funkcji `np.ravel()`.

### Miejsce na rozwiązanie

In [82]:
A = A.reshape(-1)
print(A)
A = np.ravel(A)
print(A)

[ 4.99  3.49  9.99  1.99  9.99 14.99 14.99  2.39  7.29]
[ 4.99  3.49  9.99  1.99  9.99 14.99 14.99  2.39  7.29]


## Ćwiczenie 14

Zbuduj tablicę o tym samym kształcie i typie danych co tablica A i wypełnij ją stałą wartością 0.0. Wydrukuj wynik do konsoli.

In [51]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])

Wskazówka: Użyj funkcji `np.zeros_like()`.

### Miejsce na rozwiązanie

In [52]:
B = np.zeros_like(A)
print(A)
print(B)

[[ 4.99  3.49  9.99]
 [ 1.99  9.99 14.99]
 [14.99  2.39  7.29]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Ćwiczenie 15

Zbuduj tablicę o tym samym kształcie i typie danych co tablica A i wypełnij ją stałą wartością 19.99. Wydrukuj wynik do konsoli.

In [53]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])

Wskazówka: Użyj funkcji `np.full_like()`.

### Miejsce na rozwiązanie

In [54]:
B = np.full_like(A,19.99)
print(A)
print(B)

[[ 4.99  3.49  9.99]
 [ 1.99  9.99 14.99]
 [14.99  2.39  7.29]]
[[19.99 19.99 19.99]
 [19.99 19.99 19.99]
 [19.99 19.99 19.99]]


## Ćwiczenie 16

Zbuduj dwuwymiarową tablicę - macierz dolna trójkątna. Wydrukuj wynik do konsoli.

### Miejsce na rozwiązanie

In [86]:
A = np.tril(np.ones((5,5)))
print(A)

[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]


## Ćwiczenie 17

Utwórz dowolną trójwymiarową tablicę o kształcie (2, 3, 4) i przypisz do zmiennej PBS. A następnie zapisz ją do pliku `array.npy`

### Miejsce na rozwiązanie

In [57]:
PBS = np.zeros((2,3,4))
print(PBS)
np.save('3D', PBS)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


## Ćwiczenie 18

Wygeneruj dwuwymiarową tablicę o kształcie (200, 300) wypełnioną losowymi wartościami od 0 do 255 (włącznie) o typie danych np.uint8 i przypisz do zmiennej image.

### Miejsce na rozwiązanie

In [87]:
X = np.random.randint(0,256, size=(200,300),dtype=np.uint8)
image = X
print(image)

[[ 23 217 255 ... 136 132 112]
 [ 21 136 134 ...  82 207 158]
 [111  30  31 ...   5 235  34]
 ...
 [185 178 229 ... 193 196 136]
 [  2 145 202 ... 117   3 255]
 [ 99  40 198 ...  84 174 214]]


## Ćwiczenie 19

Posortuj tablicę image wzdłuż wiersza rosnąco i przypisz do zmiennej image_sorted.

### Miejsce na rozwiązanie

In [88]:
image_sorted = np.sort(image, axis=1)
print(image_sorted)

[[  0   2   2 ... 254 255 255]
 [  2   2   3 ... 250 252 255]
 [  0   0   0 ... 254 254 255]
 ...
 [  2   2   4 ... 254 254 255]
 [  1   2   3 ... 253 253 255]
 [  0   0   0 ... 250 251 254]]


## Ćwiczenie 20

Wygeneruj dwuwymiarową tablicę o kształcie (200, 300) wypełnioną losowymi wartościami od 0 do 255 (włącznie) o typie danych np.float32 i przypisz do zmiennej. Następnie zapisz tablicę do pliku binarnego o nazwie `array_20.npy`, załaduj ten plik z powrotem do innej zmiennej i wydrukuj jej zawartość do konsoli.

Wskazówka: Użyj funkcji `np.save()` oraz `np.load()`.

### Miejsce na rozwiązanie

In [68]:
X = np.random.rand(200,300).astype(np.float32) * 255
np.save('array_20',X)
A = np.load('array_20.npy')
print(A)

[[132.48492   239.33363    38.086037  ... 142.52261    85.3831
  102.6966   ]
 [213.66263    35.12555   168.22473   ... 250.74088   225.59572
  221.11473  ]
 [ 35.64223    50.62377   135.33153   ...  16.774231  119.25204
   43.779663 ]
 ...
 [158.38591    73.5744      5.9975047 ...  31.356606  136.1045
   48.44319  ]
 [192.1205    106.38731    36.96973   ... 248.78917   215.71877
  112.3413   ]
 [ 65.295906  220.8804    109.43395   ... 105.36555    35.009964
  168.91147  ]]


# Wnioski i sugestie do ćwiczeń