In [1]:
import numpy as np

## Dane studenta

Cezary Tytko 118873

# Zadania do samodzielnego wykonania

## Ćwiczenie 1

Stwórz macierz o wymiarach 3x3, która zawiera losowe liczby całkowite z zakresu od 1 do 10.

In [2]:
macierz = np.random.randint(1, 11, (3, 3))
print(macierz)

[[7 5 8]
 [6 2 4]
 [5 7 1]]


## Ćwiczenie 2

Znajdź średnią wartość dla każdej kolumny w macierzy z poprzedniego zadania.

In [3]:
srednie_kolumn = np.mean(macierz, axis=0)
print(srednie_kolumn)

[6.         4.66666667 4.33333333]


## Ćwiczenie 3

Wykonaj operację transpozycji na wcześniej stworzonej macierzy.

In [4]:
transpozycja_macierzy = np.transpose(macierz)
print(transpozycja_macierzy)


[[7 6 5]
 [5 2 7]
 [8 4 1]]


## Ćwiczenie 4

Przemnóż dwie macierze o wymiarach 3x3, gdzie elementy są losowymi liczbami rzeczywistymi.

In [5]:
macierz1 = np.random.rand(3, 3)
macierz2 = np.random.rand(3, 3)
iloczyn_macierzy = np.dot(macierz1, macierz2)
print(iloczyn_macierzy)

[[0.96702292 1.47140204 0.55921651]
 [0.18173338 0.81715603 0.52780657]
 [0.72012883 1.129606   0.49579599]]


## Ćwiczenie 5

Znajdź indeks maksymalnej wartości w jednowymiarowej tablicy NumPy.

In [14]:
jednowymiarowa_tablica = np.random.randint(0, 10, 6)
print(jednowymiarowa_tablica)
indeks_max = np.argmax(jednowymiarowa_tablica)
print(indeks_max)

[2 3 8 8 0 7]
2


## Ćwiczenie 6

Stwórz macierz o wymiarach 4x4, wypełnioną liczbami z rozkładu normalnego.

In [15]:
macierz_normalna = np.random.randn(4, 4)
print(macierz_normalna)

[[ 0.88841385 -2.26793918 -0.78273352 -0.23088957]
 [-0.96397198  0.39677622 -0.84854017 -0.60556427]
 [-0.23453549 -1.32051911  0.2475837  -0.58210444]
 [ 0.00434343 -0.82001026 -0.79820883 -0.68163606]]


## Ćwiczenie 7

Znajdź wszystkie unikalne wartości w jednowymiarowej tablicy NumPy.

In [16]:
jednowymiarowa_unikalne = np.unique(jednowymiarowa_tablica)
print(jednowymiarowa_unikalne)

[0 2 3 7 8]


## Ćwiczenie 8

Wykorzystaj broadcasting w NumPy do przemnożenia macierzy o wymiarach (3, 4) przez wektor o długości 4.

In [22]:
macierz = np.random.rand(3, 4)
wektor = np.random.rand(4)
wynik = macierz.dot(wektor.reshape(4,1))
print(wynik)

[[0.97820362]
 [0.56556224]
 [0.66746921]]


## Ćwiczenie 9

Stwórz funkcję, która znajdzie miejsca zerowe funkcji kwadratowej, reprezentowanej przez wektory współczynników a, b i c.

In [11]:
def miejsca_zerowe(a, b, c):
    delta = b**2 - 4*a*c
    if delta > 0:
        x1 = (-b + np.sqrt(delta)) / (2*a)
        x2 = (-b - np.sqrt(delta)) / (2*a)
        return x1, x2
    elif delta == 0:
        x = -b / (2*a)
        return x,
    else:
        return "Brak miejsc zerowych dla funkcji kwadratowej."

a = 1
b = -3
c = 2
print(miejsca_zerowe(a, b, c))

(2.0, 1.0)


# Wnioski i sugestie do ćwiczeń

Wnioski: 
Były to dobre zadania podsumowujące zdobytą widzę, ćwiczenia zwierają przekrój kluczowych i najważniejszych funkcjonalności biblioteki numpy, która jest podstawowym i elementarnym narzędziem przy pracy z tablicami.